//
// Generated by JTB 1.3.2
//

package dna.ast.syntaxtree;

/**
 * Grammar production:
 * f0 -> <ENUM>
 * f1 -> ( [ <IDENTIFIER> ] "{" EnumeratorList() "}" | <IDENTIFIER> )
 */
public class EnumSpecifier implements Node {
   public NodeToken f0;
   public NodeChoice f1;

   public EnumSpecifier(NodeToken n0, NodeChoice n1) {
      f0 = n0;
      f1 = n1;
   }

   public EnumSpecifier(NodeChoice n0) {
      f0 = new NodeToken("enum");
      f1 = n0;
   }

   public void accept(dna.ast.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(dna.ast.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(dna.ast.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(dna.ast.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

