//
// Generated by JTB 1.3.2
//

package dna.ast.syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(dna.ast.visitor.Visitor v);
   public <R,A> R accept(dna.ast.visitor.GJVisitor<R,A> v, A argu);
   public <R> R accept(dna.ast.visitor.GJNoArguVisitor<R> v);
   public <A> void accept(dna.ast.visitor.GJVoidVisitor<A> v, A argu);
}

